FROM golang:1.26-alpine AS builder
ARG GOPRIVATE
ARG GITHUB_TOKEN
ENV GO111MODULE=on
ENV XDG_CACHE_HOME="/go/src/github.com/mdblp/.cache"
WORKDIR /go/src/github.com/mdblp/
# gcc and musl-dev are needed to build some of the dependencies,
# this docker image is not the one used to build and push the data service
RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache gcc musl-dev git rsync python3 python3-dev pipx make tzdata && \
    adduser -D mdblp && \
    chown -R mdblp /go
USER mdblp
RUN  pipx install prance[cli,osv]
ENV PATH="$PATH:/home/mdblp/.local/bin"
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
COPY --chown=mdblp  go.mod ./
COPY --chown=mdblp go.sum ./
RUN ls -al && go mod download
