# Development
FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS development
ARG GOPRIVATE
ARG GITHUB_TOKEN
ENV GO111MODULE on
WORKDIR /go/src/github.com/tidepool-org/platform
RUN apk --no-cache add git make tzdata && \
    apk add --no-cache ca-certificates tzdata git && \
    go install github.com/githubnemo/CompileDaemon@latest && \
    adduser -D tidepool && \
    chown -R tidepool /go/pkg/mod

COPY . .
RUN chown -R tidepool /go/src/github.com/tidepool-org/platform

USER tidepool
ENV SERVICE=services/data
ARG TARGETPLATFORM
ARG BUILDPLATFORM
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
RUN ["make", "service-build"]
CMD ["make", "service-start"]

# Production
FROM gcr.io/distroless/static:nonroot AS production
WORKDIR /home/mdblp
USER nonroot
ENV ZONEINFO=/usr/local/go/lib/time/zoneinfo.zip
COPY --from=development --chown=nonroot /go/src/github.com/tidepool-org/platform/_bin/services/data/ .
COPY --from=development --chown=nonroot /usr/local/go/lib/time/zoneinfo.zip /usr/local/go/lib/time/
CMD ["./data"]
